site_name: Documentacion del proyecto final de fisica computacional 
nav:
  - Inicio: index.md
  - Tutorial: tutorial.md
  - Documentacion: documentacion.md

theme:
  name: material
  language: es

plugins:
  - search
  - mkdocstrings:

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - admonition              
  - pymdownx.details        
  - pymdownx.superfences   
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - toc:
      permalink: true      

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

site_url: https://Klpz0.github.io/Proyecto_Final_FS-0432/
